[package]
name = "blueprint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
clap_derive = "3.2.7"
nom = "7.1.1"
pest = "2.1.3"
pest_derive = "2.1.0"
